import Config

# Configure your database
config :ex_jagaimo_blog, ExJagaimoBlog.Repo,
  username: "postgres",
  password: "postgres",
  database: "exjagaimoblog_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :ex_jagaimo_blog, ExJagaimoBlog.Search.Cluster,
  #  url: "https://localhost:9200",
  #  username: elastic_username,
  #  password: elastic_password,
  # obviously a bad solution in prod, but for now it works
  http_client_adapter:
    {Snap.HTTPClient.Adapters.Finch,
     pool_size: 20, conn_opts: [transport_opts: [verify: :verify_peer, cacertfile: 'priv/dev/http_ca.crt']]}

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :ex_jagaimo_blog, ExJagaimoBlogWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch",
      "--watch-options-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ],
  domain_opts: [
    host_suffix: ".localtest.me",
    optional_suffixes: [".localtest.me"]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ex_jagaimo_blog, ExJagaimoBlogWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ex_jagaimo_blog_web/(live|views)/.*(ex)$",
      ~r"lib/ex_jagaimo_blog_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
